<?php
$data = array (
  17 => 
  array (
    'cat_id' => '17',
    'cat_name' => '图书',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '6',
    'goods_num' => 0,
    'level' => 0,
    'id' => '17',
    'name' => '图书',
  ),
  19 => 
  array (
    'cat_id' => '19',
    'cat_name' => '少儿',
    'measure_unit' => '',
    'parent_id' => '17',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '19',
    'name' => '少儿',
  ),
  18 => 
  array (
    'cat_id' => '18',
    'cat_name' => '文学',
    'measure_unit' => '',
    'parent_id' => '17',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '1',
    'goods_num' => '1',
    'level' => 1,
    'id' => '18',
    'name' => '文学',
  ),
  24 => 
  array (
    'cat_id' => '24',
    'cat_name' => '娱乐',
    'measure_unit' => '',
    'parent_id' => '18',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '24',
    'name' => '娱乐',
  ),
  23 => 
  array (
    'cat_id' => '23',
    'cat_name' => '计算机与互联网',
    'measure_unit' => '',
    'parent_id' => '17',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '23',
    'name' => '计算机与互联网',
  ),
  20 => 
  array (
    'cat_id' => '20',
    'cat_name' => '教育',
    'measure_unit' => '',
    'parent_id' => '17',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '20',
    'name' => '教育',
  ),
  21 => 
  array (
    'cat_id' => '21',
    'cat_name' => '管理',
    'measure_unit' => '',
    'parent_id' => '17',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '21',
    'name' => '管理',
  ),
  22 => 
  array (
    'cat_id' => '22',
    'cat_name' => '科学',
    'measure_unit' => '',
    'parent_id' => '17',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '22',
    'name' => '科学',
  ),
);
?>