<?php
$data = array (
  1 => 
  array (
    'cat_id' => '1',
    'cat_name' => '手机游戏',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '7',
    'goods_num' => 0,
    'level' => 0,
    'id' => '1',
    'name' => '手机游戏',
  ),
  8 => 
  array (
    'cat_id' => '8',
    'cat_name' => '棋牌娱乐',
    'measure_unit' => '',
    'parent_id' => '1',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '8',
    'name' => '棋牌娱乐',
  ),
  5 => 
  array (
    'cat_id' => '5',
    'cat_name' => '休闲益智',
    'measure_unit' => '',
    'parent_id' => '1',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '5',
    'name' => '休闲益智',
  ),
  2 => 
  array (
    'cat_id' => '2',
    'cat_name' => '女孩专题',
    'measure_unit' => '',
    'parent_id' => '1',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '2',
    'name' => '女孩专题',
  ),
  6 => 
  array (
    'cat_id' => '6',
    'cat_name' => '角色扮演',
    'measure_unit' => '',
    'parent_id' => '1',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '6',
    'name' => '角色扮演',
  ),
  3 => 
  array (
    'cat_id' => '3',
    'cat_name' => '体育竞技',
    'measure_unit' => '',
    'parent_id' => '1',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '3',
    'name' => '体育竞技',
  ),
  7 => 
  array (
    'cat_id' => '7',
    'cat_name' => '飞行射击',
    'measure_unit' => '',
    'parent_id' => '1',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '7',
    'name' => '飞行射击',
  ),
  4 => 
  array (
    'cat_id' => '4',
    'cat_name' => '模拟游戏',
    'measure_unit' => '',
    'parent_id' => '1',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '4',
    'name' => '模拟游戏',
  ),
  20 => 
  array (
    'cat_id' => '20',
    'cat_name' => '手机动漫',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '2',
    'level' => 0,
    'id' => '20',
    'name' => '手机动漫',
  ),
  18 => 
  array (
    'cat_id' => '18',
    'cat_name' => '电子漫画',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '1',
    'goods_num' => 0,
    'level' => 0,
    'id' => '18',
    'name' => '电子漫画',
  ),
  19 => 
  array (
    'cat_id' => '19',
    'cat_name' => '搞笑',
    'measure_unit' => '',
    'parent_id' => '18',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '19',
    'name' => '搞笑',
  ),
  14 => 
  array (
    'cat_id' => '14',
    'cat_name' => '旅游产品',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '2',
    'goods_num' => 0,
    'level' => 0,
    'id' => '14',
    'name' => '旅游产品',
  ),
  16 => 
  array (
    'cat_id' => '16',
    'cat_name' => '境外旅游',
    'measure_unit' => '',
    'parent_id' => '14',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '16',
    'name' => '境外旅游',
  ),
  15 => 
  array (
    'cat_id' => '15',
    'cat_name' => '国内旅游',
    'measure_unit' => '',
    'parent_id' => '14',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '15',
    'name' => '国内旅游',
  ),
);
?>