<?php
$data = array (
  18 => 
  array (
    'cat_id' => '18',
    'cat_name' => '美食',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '1',
    'has_children' => '5',
    'goods_num' => '1',
    'level' => 0,
    'id' => '18',
    'name' => '美食',
  ),
  27 => 
  array (
    'cat_id' => '27',
    'cat_name' => '陕西菜',
    'measure_unit' => '',
    'parent_id' => '18',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '0',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '27',
    'name' => '陕西菜',
  ),
  20 => 
  array (
    'cat_id' => '20',
    'cat_name' => '火锅',
    'measure_unit' => '',
    'parent_id' => '18',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '0',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '20',
    'name' => '火锅',
  ),
  28 => 
  array (
    'cat_id' => '28',
    'cat_name' => '川菜',
    'measure_unit' => '',
    'parent_id' => '18',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '0',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '28',
    'name' => '川菜',
  ),
  26 => 
  array (
    'cat_id' => '26',
    'cat_name' => '西餐',
    'measure_unit' => '',
    'parent_id' => '18',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '0',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '26',
    'name' => '西餐',
  ),
  29 => 
  array (
    'cat_id' => '29',
    'cat_name' => '面食',
    'measure_unit' => '',
    'parent_id' => '18',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '29',
    'name' => '面食',
  ),
  19 => 
  array (
    'cat_id' => '19',
    'cat_name' => '酒店',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '2',
    'has_children' => '3',
    'goods_num' => 0,
    'level' => 0,
    'id' => '19',
    'name' => '酒店',
  ),
  34 => 
  array (
    'cat_id' => '34',
    'cat_name' => '四星级',
    'measure_unit' => '',
    'parent_id' => '19',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '20',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '34',
    'name' => '四星级',
  ),
  33 => 
  array (
    'cat_id' => '33',
    'cat_name' => '五星级',
    'measure_unit' => '',
    'parent_id' => '19',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '30',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '33',
    'name' => '五星级',
  ),
  35 => 
  array (
    'cat_id' => '35',
    'cat_name' => '快捷酒店',
    'measure_unit' => '',
    'parent_id' => '19',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '35',
    'name' => '快捷酒店',
  ),
  23 => 
  array (
    'cat_id' => '23',
    'cat_name' => '丽人',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '3',
    'has_children' => '2',
    'goods_num' => 0,
    'level' => 0,
    'id' => '23',
    'name' => '丽人',
  ),
  30 => 
  array (
    'cat_id' => '30',
    'cat_name' => '美甲',
    'measure_unit' => '',
    'parent_id' => '23',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '30',
    'name' => '美甲',
  ),
  31 => 
  array (
    'cat_id' => '31',
    'cat_name' => '美容美发',
    'measure_unit' => '',
    'parent_id' => '23',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '31',
    'name' => '美容美发',
  ),
  25 => 
  array (
    'cat_id' => '25',
    'cat_name' => '结婚',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '4',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 0,
    'id' => '25',
    'name' => '结婚',
  ),
  24 => 
  array (
    'cat_id' => '24',
    'cat_name' => '亲子',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '5',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 0,
    'id' => '24',
    'name' => '亲子',
  ),
  22 => 
  array (
    'cat_id' => '22',
    'cat_name' => '休闲',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '6',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 0,
    'id' => '22',
    'name' => '休闲',
  ),
);
?>